hello:
- test
packs:
  behavior:
    format_version: 2
    header:
      name: map-template
      description: 'map-template: Resource Pack'
      version:
      - 1
      - 0
      - 0
      min_engine_version: [1, 19, 50]
      uuid: 89d1b3c6-3fd9-4789-952a-70e5c3077d9c
    modules:
    - type: data
      uuid: a392c333-d298-4cd0-8caa-13a069234d25
      version:
      - 1
      - 0
      - 0
    dependencies:
    - uuid: 6fcb47c3-50f6-41b7-a75d-bb94f80847e0
      version: &ref_0
      - 1
      - 0
      - 0
  resource:
    format_version: 2
    header:
      name: map-template
      description: 'map-template: Resource Pack'
      version: *ref_0
      min_engine_version: [1, 19, 50]
      uuid: 6fcb47c3-50f6-41b7-a75d-bb94f80847e0
    modules:
    - type: resources
      uuid: b383df33-a2b3-446e-b2e7-cdba15ab4066
      version:
      - 1
      - 0
      - 0
